### ISSUE TITLE
Issue on personal profile and update page

### ISSUE THREAD

**Issue by shreyas1307** [Robert-Fish/DevUp#1]
1) The contents of the form on the profile update page over-flow. Below is a reference 
![image](https://user-images.githubusercontent.com/45281085/55459749-dfc05c00-560d-11e9-90ad-7d0f6786c372.png)

Also, the font size could be heavier and bigger too.

2) I think this should be centered. Also, the delete account button seems to get more attention than the edit profile, so users may accidentally click it.
![image](https://user-images.githubusercontent.com/45281085/55460101-b5bb6980-560e-11e9-991d-cb5ad5bdb3ae.png)

3) Adjusting the spacing of elements on the left and right of the container. The image block has less space from the left of the container compared to the skill set on the right-side of the container
![image](https://user-images.githubusercontent.com/45281085/55460078-a4725d00-560e-11e9-8e4f-270d6759632e.png)

**Comment by Robert-Fish** [comment]
I've fixed all the issues except for the containers on the profile page. For those, i'm doing a new design.
I'll close the issue for now but feel free to re-open if you have any questions.
